//Entry point
GET http://localhost:8000/

###

#List users
GET http://localhost:8000/api/users

###

#find user
GET http://localhost:8000/api/users/1

###

//Create user
POST http://localhost:8000/api/users
Content-Type: application/json

{
    "name": "tilin", 
    "username": "tilinInsano", 
    "password": "1234"
}

###

PUT http://localhost:8000/api/users/1
Content-Type: application/json

{
    "name": "hanzeel", 
    "username": "walle", 
    "password": "1234"
}

###

DELETE http://localhost:8000/api/users/1